sudo: required
dist: trusty
language: generic
services:
  - docker
cache:
  directories:
  - .cache
branches:
  only:
    - /^20.*$/
    - master

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    env:
     - LABEL="amd64_linux"
  - os: linux
    env:
     - LABEL="armhf_linux"
  - os: linux
    env:
     - LABEL="arm64_linux"
    
notifications:
  email: false
  
before_install:
  - docker pull headmelted/cobbler;

script:
  - cd kitchen;
  # - if [[ "${TRAVIS_TAG}" =~ ^20.*$ ]]; then
  - sudo bash -c ". ./tools/dock.sh headmelted/cobbler \"tools/cook.sh ${LABEL} get patch build package\""
  # else
  #     if [[ "${LABEL}" == "armhf_linux" ]]; then
  #       echo "Merging packages repository back up to Github Pages...";
  #       . ./tools/merge.sh;
  #     fi;
  #   fi;

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - ./kitchen/.builds/**/*.deb
    - ./kitchen/.builds/**/*.rpm
    - ./kitchen/.builds/**/*.tar.gz
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
