sudo: required
dist: trusty
language: generic
services:
  - docker
cache:
  directories:
    - ./cache
branches:
  only:
    - /^2017.*$/
        
# linux amd64 toolchain
include: &toolchain_linux_amd64
  env:
    - LABEL=amd64_linux
    - ARCH=amd64
    - GPP_COMPILER=g++-4.9
    - GCC_COMPILER=gcc-4.9
    - VSCODE_ELECTRON_PLATFORM=x64
    - PACKAGE_ARCH=x64
  
# armhf toolchain
include: &toolchain_linux_armhf
  env:
    - LABEL=armhf_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=armhf
    - NPM_ARCH=arm
    - GNU_TRIPLET=arm-linux-gnueabihf
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=arm-linux-gnueabihf-g++
    - GCC_COMPILER=arm-linux-gnueabihf-gcc
    - VSCODE_ELECTRON_PLATFORM=arm
    - PACKAGE_ARCH=armhf
    - QEMU_ARCH=arm
  
# arm64 toolchain
include: &toolchain_linux_arm64
  env:
    - LABEL=arm64_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=arm64
    - NPM_ARCH=arm
    - GNU_TRIPLET=aarch64-linux-gnu
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=aarch64-linux-gnu-g++
    - GCC_COMPILER=aarch64-linux-gnu-gcc
    - VSCODE_ELECTRON_PLATFORM=arm
    - PACKAGE_ARCH=arm64
    - QEMU_ARCH=aarch64
    
# amd64 toolchain for flatpak builds
include: &toolchain_linux_amd64_flatpak
  env:
    - LABEL=amd64_flatpak
    - VSCODE_ELECTRON_PLATFORM=x64
    - FLATPAK_ISOLATED_BUILD=true
    
# i386 toolchain for flatpak builds
include: &toolchain_linux_i386_flatpak
  env:
    - LABEL=i386_flatpak
    - CROSS_TOOLCHAIN=true
    - VSCODE_ELECTRON_PLATFORM=i386
    - FLATPAK_ISOLATED_BUILD=true
    
# arm toolchain for flatpak builds
include: &toolchain_linux_arm_flatpak
  env:
    - LABEL=arm_flatpak
    - CROSS_TOOLCHAIN=true
    - VSCODE_ELECTRON_PLATFORM=arm
    - FLATPAK_ISOLATED_BUILD=true

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    <<: *toolchain_linux_amd64
  - os: linux
    <<: *toolchain_linux_armhf
  - os: linux
    <<: *toolchain_linux_arm64
  - os: linux
    <<: *toolchain_linux_amd64_flatpak
  - os: linux
    <<: *toolchain_linux_i386_flatpak
  - os: linux
    <<: *toolchain_linux_arm_flatpak
    
notifications:
  email: false
  
script:
  - export UBUNTU_VERSION="xenial";
  - if [ "${FLATPAK_ISOLATED_BUILD}" == "true" ]; then
      dock_script="./codebuilds-tools/flatpak/build.sh";
    else
      dock_script="./codebuilds-tools/travis_build.sh";
    fi;
  - . ./codebuilds-tools/dock.sh "ubuntu:${UBUNTU_VERSION}" $dock_script;

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - .build/linux/**/*.deb
    - .build/linux/**/*.rpm
    - .build/linux/**/*.flatpak
    - ./buildlog_*.txt
    - ./archive_*.tar.gz
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
    
after_deploy:
  - cd codebuilds-tools;
  - bash ./pushToBintray.sh $(find ../.build/linux -type f -name "*.deb");
  - bash ./pushToBintray.sh $(find ../.build/linux -type f -name "*.rpm");
