sudo: required
dist: trusty
language: generic
cache:
  directories:
  - cache
branches:
  only:
    - /^20.*$/
    - master

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    env:
     - LABEL="amd64_linux"
  - os: linux
    env:
     - LABEL="armhf_linux"
  - os: linux
    env:
     - LABEL="arm64_linux"
    
notifications:
  email: false

script:
  - if [[ "${TRAVIS_TAG}" =~ ^20.*$ ]]; then
      sudo bash -c ". ./codebuilds-tools/all.sh ${LABEL}";
   else
      if [[ "${LABEL}" == "armhf_linux" ]]; then
        echo "Merging packages repository back up to Github Pages...";
        . ./codebuilds-tools/merge.sh;
      fi;
    fi;

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - .build/linux/**/*.deb
    - .build/linux/**/*.rpm
    - .build/linux/**/*.flatpak
    - ./buildlog_*.txt
    - ./archive_*.tar.gz
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
  