sudo: required
dist: trusty
language: generic
services:
  - docker
cache:
  directories:
    - ./cache
branches:
  only:
    - /^2017.*$/
    - master
        
# linux amd64 toolchain
include: &toolchain_linux_amd64
  env:
    - LABEL=amd64_linux
    - ARCH=amd64
    - GPP_COMPILER=g++-4.9
    - GCC_COMPILER=gcc-4.9
    - VSCODE_ELECTRON_PLATFORM=x64
    - PACKAGE_ARCH=x64
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
  
# armhf toolchain
include: &toolchain_linux_armhf
  env:
    - LABEL=armhf_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=armhf
    - NPM_ARCH=arm
    - GNU_TRIPLET=arm-linux-gnueabihf
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=arm-linux-gnueabihf-g++
    - GCC_COMPILER=arm-linux-gnueabihf-gcc
    - VSCODE_ELECTRON_PLATFORM=arm
    - PACKAGE_ARCH=armhf
    - QEMU_ARCH=arm
    - QEMU_IMAGE="https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-04-10/2017-04-10-raspbian-jessie-lite.zip"
    - QEMU_KERNEL="kernel7.img"
    - QEMU_DTB="bcm2709-rpi-2-b.dtb"
    - QEMU_MACHINE="raspi2"
  
# arm64 toolchain
include: &toolchain_linux_arm64
  env:
    - LABEL=arm64_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=arm64
    - NPM_ARCH=arm
    - GNU_TRIPLET=aarch64-linux-gnu
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=aarch64-linux-gnu-g++
    - GCC_COMPILER=aarch64-linux-gnu-gcc
    - VSCODE_ELECTRON_PLATFORM=arm
    - PACKAGE_ARCH=arm64
    - QEMU_ARCH=aarch64
    - QEMU_IMAGE="https://dl.armbian.com/odroidc2/Ubuntu_xenial_default.7z"
    - QEMU_KERNEL="Image"
    - QEMU_DTB="meson64_odroidc2.dtb"
    - QEMU_MACHINE="virt"

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    <<: *toolchain_linux_amd64
  - os: linux
    <<: *toolchain_linux_armhf
  - os: linux
    <<: *toolchain_linux_arm64
    
notifications:
  email: false
  
script:
  - sudo ln -s ${TRAVIS_BUILD_DIR} /workspace;
  - export TRAVIS_BUILD_DIR=/workspace;
  - export UBUNTU_VERSION="yakkety";
  - sudo bash -c ". /workspace/codebuilds-tools/all.sh";
  - if [ "${QEMU_ARCH}" != "" ]; then
      . /workspace/codebuilds-tools/prepare_virtual_device.sh;
      . /workspace/codebuilds-tools/emulate.sh '/workspace/codebuilds-tools/install_package_and_test.sh';
    else
      . /workspace/codebuilds-tools/install_package_and_test.sh;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - .build/linux/**/*.deb
    - .build/linux/**/*.rpm
    - .build/linux/**/*.flatpak
    - ./buildlog_*.txt
    - ./archive_*.tar.gz
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
    
after_deploy:
  # - cd codebuilds-tools;
  # - bash ./pushToBintray.sh $(find ../.build/linux -type f -name "*.deb");
  # - bash ./pushToBintray.sh $(find ../.build/linux -type f -name "*.rpm");
  - if [[ ! "${TRAVIS_TAG}" =~ ^2017.*$ ]]; then
      mkdir /workspace/docs/packages /workspace/docs/packages/apt;
      debfile=$(find /workspace/.build/linux -type f -name "*.deb");
      cp $debfile /workspace/docs/packages/apt/;
      dpkg-scanpackages -m docs/packages/apt/ | gzip -c > /workspace/docs/packages/apt/Packages.gz;
      . /workspace/codebuilds-tools/merge.sh;
    fi;
  